---
applications:
- name: eqip-prototype-api-staging
  memory: 64M
  instances: 2
  domain: fr.cloud.gov
  host: eqip-prototype-api-staging
  buildpack: https://github.com/cloudfoundry/go-buildpack
  path: ../../api
  command: ./api
  services:
    - eqip-postgres
    - usps-api
  env:
    PATH: /bin:/usr/bin:$HOME/bin
    GOVERSION: go1.10
    GOLANG_ENV: development
    LOG_LEVEL: debug
    CORS_ALLOWED: https://eqip-prototype-staging.fr.cloud.gov
    API_REDIRECT: https://eqip-prototype-staging.fr.cloud.gov
    API_BASE_URL: https://eqip-prototype-api-staging.fr.cloud.gov
    ALLOW_2FA_RESET: 1
    BASIC_ENABLED: 1
    SAML_ENABLED: 1
    SAML_PUBLIC_CERT: eapp.crt
    SAML_PRIVATE_CERT: eapp.key
    SAML_IDP_SSO_URL: https://ids.kxsolutions.com:8443/samlsso
    SAML_IDP_SSO_DESC_URL: fr.cloud.gov
    SAML_IDP_PUBLIC_CERT: kx.crt
    SAML_SIGN_REQUEST: 1
    SAML_CONSUMER_SERVICE_URL: https://eqip-prototype-api-staging.fr.cloud.gov/auth/saml/callback
